'use client';
import{useState}from'react';import{supabase}from'../../../lib/supabase';
type Rating={rating_id:string;book_title:string;book_author:string;display_name:string;hook_score:number;story_score:number;overall_score:number;created_at:string};type Post={post_id:string;book_title:string;display_name:string;post_type:string;title:string;body:string;created_at:string};type Book={id:string;title:string;author:string;meeting_date:string|null;status:string};
const box={padding:18,borderRadius:18,background:'rgba(255,255,255,.72)',border:'1px solid #dce8f7'} as const;const field={padding:'12px 14px',borderRadius:13,border:'1px solid #c9d9ee',fontSize:15,width:'100%'} as const;const btn={padding:'11px 15px',border:0,borderRadius:13,background:'#173f78',color:'white',fontWeight:800,cursor:'pointer'} as const;
export default function Admin(){const[password,setPassword]=useState(''),[unlocked,setUnlocked]=useState(false),[tab,setTab]=useState<'ratings'|'board'|'books'>('ratings'),[ratings,setRatings]=useState<Rating[]>([]),[posts,setPosts]=useState<Post[]>([]),[books,setBooks]=useState<Book[]>([]),[error,setError]=useState(''),[newTitle,setNewTitle]=useState(''),[newAuthor,setNewAuthor]=useState(''),[newDate,setNewDate]=useState(''),[newStatus,setNewStatus]=useState('upcoming');
async function load(){if(!supabase)return;setError('');const[{data:r,error:e},{data:p},{data:b}]=await Promise.all([supabase.rpc('literal_trash_admin_list_ratings',{admin_password:password}),supabase.rpc('literal_trash_admin_list_board',{admin_password:password}),supabase.rpc('literal_trash_admin_list_books',{admin_password:password})]);if(e){setError('That password is not correct.');setUnlocked(false);return}setRatings((r||[])as Rating[]);setPosts((p||[])as Post[]);setBooks((b||[])as Book[]);setUnlocked(true)}
async function deleteRating(id:string){if(!supabase||!confirm('Delete this rating?'))return;await supabase.rpc('literal_trash_admin_delete_rating',{admin_password:password,target_rating_id:id});void load()}
async function deletePost(id:string){if(!supabase||!confirm('Delete this board post?'))return;await supabase.rpc('literal_trash_admin_delete_board_post',{admin_password:password,target_post_id:id});void load()}
async function editPost(p:Post){if(!supabase)return;const title=prompt('Edit title',p.title);if(title===null)return;const body=prompt('Edit post',p.body);if(body===null)return;await supabase.rpc('literal_trash_admin_update_board_post',{admin_password:password,target_post_id:p.post_id,new_type:p.post_type,new_title:title,new_body:body});void load()}
async function addBook(){if(!supabase||!newTitle.trim()||!newAuthor.trim())return;const{error:e}=await supabase.rpc('literal_trash_admin_save_book',{admin_password:password,target_book_id:null,new_title:newTitle,new_author:newAuthor,new_meeting_date:newDate||null,new_status:newStatus});if(e){setError(e.message);return}setNewTitle('');setNewAuthor('');setNewDate('');void load()}
async function changeStatus(b:Book,status:string){if(!supabase)return;const{error:e}=await supabase.rpc('literal_trash_admin_save_book',{admin_password:password,target_book_id:b.id,new_title:b.title,new_author:b.author,new_meeting_date:b.meeting_date,new_status:status});if(e)setError(e.message);else void load()}
async function deleteBook(b:Book){if(!supabase||!confirm(`Delete ${b.title}? This also deletes its scores and archived board.`))return;await supabase.rpc('literal_trash_admin_delete_book',{admin_password:password,target_book_id:b.id});void load()}
return <main style={{minHeight:'100vh',padding:'40px 20px',background:'linear-gradient(145deg,#f8fcff,#e8f2ff)'}}><div style={{maxWidth:1100,margin:'auto'}}><a href="/" style={{color:'#193f78',fontWeight:800,textDecoration:'none'}}>← Back to Literal Trash</a><div style={{...box,marginTop:20,padding:30}}><div style={{fontSize:12,letterSpacing:2,textTransform:'uppercase',fontWeight:900,color:'#5576aa'}}>Literal Trash Admin</div><h1 style={{fontFamily:'Georgia,serif',fontSize:52,color:'#102d59',margin:'8px 0'}}>Club Control Room</h1>{!unlocked?<form onSubmit={e=>{e.preventDefault();void load()}} style={{maxWidth:430,display:'flex',gap:9}}><input style={field} type="password" placeholder="Admin password" value={password} onChange={e=>setPassword(e.target.value)}/><button style={btn}>Log in</button></form>:<><div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'20px 0'}}>{(['ratings','board','books']as const).map(t=><button key={t} style={{...btn,background:tab===t?'#173f78':'#dceaff',color:tab===t?'white':'#173f78'}} onClick={()=>setTab(t)}>{t==='ratings'?'Scores':t==='board'?'Discussion Board':'Books & Archive'}</button>)}</div>
{tab==='ratings'&&<div style={{display:'grid',gap:10}}>{ratings.map(r=><div key={r.rating_id} style={{...box,display:'grid',gridTemplateColumns:'1.2fr 1.4fr repeat(3,.6fr) auto',gap:12,alignItems:'center'}}><strong>{r.display_name}</strong><span>{r.book_title}</span><span>Hook<br/><b>{Number(r.hook_score).toFixed(2)}</b></span><span>Story<br/><b>{Number(r.story_score).toFixed(2)}</b></span><span>Overall<br/><b>{Number(r.overall_score).toFixed(2)}</b></span><button style={{...btn,background:'#9a3152'}} onClick={()=>void deleteRating(r.rating_id)}>Delete</button></div>)}</div>}
{tab==='board'&&<div style={{display:'grid',gap:10}}>{posts.map(p=><div key={p.post_id} style={box}><div style={{fontSize:12,color:'#6881a6',fontWeight:800}}>{p.book_title||'Unassigned'} · {p.post_type} · {p.display_name}</div><h3 style={{margin:'7px 0'}}>{p.title}</h3><p>{p.body}</p><div style={{display:'flex',gap:8}}><button style={btn} onClick={()=>void editPost(p)}>Edit</button><button style={{...btn,background:'#9a3152'}} onClick={()=>void deletePost(p.post_id)}>Delete</button></div></div>)}</div>}
{tab==='books'&&<><div style={{...box,marginBottom:18}}><h3 style={{marginTop:0}}>Add a book</h3><div style={{display:'grid',gridTemplateColumns:'1.2fr 1fr .7fr .7fr auto',gap:8}}><input style={field} placeholder="Book title" value={newTitle} onChange={e=>setNewTitle(e.target.value)}/><input style={field} placeholder="Author" value={newAuthor} onChange={e=>setNewAuthor(e.target.value)}/><input style={field} type="date" value={newDate} onChange={e=>setNewDate(e.target.value)}/><select style={field} value={newStatus} onChange={e=>setNewStatus(e.target.value)}><option value="upcoming">Upcoming</option><option value="current">Current</option><option value="past">Past</option></select><button style={btn} onClick={()=>void addBook()}>Add</button></div></div><div style={{display:'grid',gap:9}}>{books.map(b=><div key={b.id} style={{...box,display:'flex',justifyContent:'space-between',alignItems:'center',gap:15,flexWrap:'wrap'}}><div><strong>{b.title}</strong><div style={{fontSize:13,color:'#6881a6'}}>{b.author} · {b.meeting_date||'No date'} · <b>{b.status}</b></div></div><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button style={btn} onClick={()=>void changeStatus(b,'current')}>Make Current</button><button style={{...btn,background:'#4f76aa'}} onClick={()=>void changeStatus(b,'upcoming')}>Upcoming</button><button style={{...btn,background:'#7890b2'}} onClick={()=>void changeStatus(b,'past')}>Archive</button><button style={{...btn,background:'#9a3152'}} onClick={()=>void deleteBook(b)}>Delete</button></div></div>)}</div></>}
</>}{error&&<p style={{color:'#9a3152',fontWeight:800}}>{error}</p>}</div></div></main>}
