'use client';
import{useState}from'react';import{supabase}from'../../../lib/supabase';
type Member={id:string;name:string;phone:string|null;email:string|null;city:string|null;state:string|null;active:boolean};
const box={padding:18,borderRadius:18,background:'rgba(255,255,255,.78)',border:'1px solid #dce8f7'} as const;const field={padding:'11px 12px',borderRadius:12,border:'1px solid #c9d9ee',fontSize:14,width:'100%',boxSizing:'border-box' as const};const btn={padding:'11px 15px',border:0,borderRadius:13,background:'#173f78',color:'white',fontWeight:800,cursor:'pointer'} as const;
export default function MembersAdmin(){const[password,setPassword]=useState(''),[unlocked,setUnlocked]=useState(false),[members,setMembers]=useState<Member[]>([]),[error,setError]=useState(''),[saved,setSaved]=useState('');
async function load(){if(!supabase)return;setError('');const{data,error:e}=await supabase.rpc('literal_trash_admin_list_members',{admin_password:password});if(e){setError('That password is not correct.');setUnlocked(false);return}setMembers((data||[])as Member[]);setUnlocked(true)}
function change(id:string,key:keyof Member,value:string|boolean){setMembers(ms=>ms.map(m=>m.id===id?{...m,[key]:value}:m))}
async function save(m:Member){if(!supabase)return;setSaved('');const{error:e}=await supabase.rpc('literal_trash_admin_update_member',{admin_password:password,target_member_id:m.id,new_name:m.name,new_phone:m.phone||'',new_email:m.email||'',new_city:m.city||'',new_state:m.state||'',new_active:m.active});if(e)setError(e.message);else{setError('');setSaved(`${m.name} saved.`);void load()}}
return <main style={{minHeight:'100vh',padding:'40px 20px',background:'linear-gradient(145deg,#f8fcff,#e8f2ff)'}}><div style={{maxWidth:1100,margin:'auto'}}><div style={{display:'flex',gap:16,flexWrap:'wrap'}}><a href="/" style={{color:'#193f78',fontWeight:800,textDecoration:'none'}}>← Back to Literal Trash</a><a href="/admin/ratings" style={{color:'#193f78',fontWeight:800,textDecoration:'none'}}>Club Control Room</a></div><div style={{...box,marginTop:20,padding:30}}><div style={{fontSize:12,letterSpacing:2,textTransform:'uppercase',fontWeight:900,color:'#5576aa'}}>Literal Trash Admin</div><h1 style={{fontFamily:'Georgia,serif',fontSize:48,color:'#102d59',margin:'8px 0'}}>Book Club Members</h1><p style={{color:'#607ca5'}}>Edit names, phone numbers, emails and locations here. Changes save to the member directory.</p>{!unlocked?<form onSubmit={e=>{e.preventDefault();void load()}} style={{maxWidth:430,display:'flex',gap:9}}><input style={field} type="password" placeholder="Admin password" value={password} onChange={e=>setPassword(e.target.value)}/><button style={btn}>Log in</button></form>:<div style={{display:'grid',gap:12}}>{members.filter(m=>m.active).map(m=><div key={m.id} style={box}><div style={{display:'grid',gridTemplateColumns:'1.2fr 1fr 1.5fr 1fr .45fr auto',gap:8,alignItems:'end'}}><label style={{fontSize:12,fontWeight:800}}>Name<input style={field} value={m.name} onChange={e=>change(m.id,'name',e.target.value)}/></label><label style={{fontSize:12,fontWeight:800}}>Phone<input style={field} value={m.phone||''} onChange={e=>change(m.id,'phone',e.target.value)}/></label><label style={{fontSize:12,fontWeight:800}}>Email<input style={field} value={m.email||''} onChange={e=>change(m.id,'email',e.target.value)}/></label><label style={{fontSize:12,fontWeight:800}}>City<input style={field} value={m.city||''} onChange={e=>change(m.id,'city',e.target.value)}/></label><label style={{fontSize:12,fontWeight:800}}>State<input style={field} maxLength={2} value={m.state||''} onChange={e=>change(m.id,'state',e.target.value.toUpperCase())}/></label><button style={btn} onClick={()=>void save(m)}>Save</button></div></div>)}</div>}{saved&&<p style={{color:'#39704c',fontWeight:800}}>{saved}</p>}{error&&<p style={{color:'#9a3152',fontWeight:800}}>{error}</p>}</div></div></main>}
