'use client';
import {useEffect,useMemo,useState} from 'react';
import {Heart,UsersRound,Sparkles} from 'lucide-react';
import {supabase} from '@/lib/supabase';
type Member={id:string;name:string};
type Score={member_id:string|null;book_id:string;hook_score:number;story_score:number};
export default function BookTwin(){
 const[members,setMembers]=useState<Member[]>([]),[scores,setScores]=useState<Score[]>([]),[memberId,setMemberId]=useState('');
 async function load(){if(!supabase)return;const[{data:m},{data:s}]=await Promise.all([supabase.from('literal_trash_members').select('id,name').eq('active',true).order('name'),supabase.from('literal_trash_scores').select('member_id,book_id,hook_score,story_score').not('member_id','is',null)]);setMembers((m||[])as Member[]);setScores((s||[])as Score[])}
 useEffect(()=>{void load();if(!supabase)return;const ch=supabase.channel('book-twin-live').on('postgres_changes',{event:'*',schema:'public',table:'literal_trash_scores'},()=>void load()).subscribe();return()=>{void supabase?.removeChannel(ch)}},[]);
 const result=useMemo(()=>{if(!memberId)return null;const mine=scores.filter(s=>s.member_id===memberId),myMap=new Map(mine.map(s=>[s.book_id,s]));const matches=members.filter(m=>m.id!==memberId).map(m=>{const theirs=scores.filter(s=>s.member_id===m.id&&myMap.has(s.book_id));if(!theirs.length)return null;let diff=0;for(const t of theirs){const a=myMap.get(t.book_id)!;diff+=(Math.abs(Number(a.hook_score)-Number(t.hook_score))+Math.abs(Number(a.story_score)-Number(t.story_score)))/2}const avgDiff=diff/theirs.length;const raw=Math.max(0,100-(avgDiff/5*100));const confidence=Math.min(1,theirs.length/3);const compatibility=Math.round(raw*(.82+.18*confidence));return{member:m,common:theirs.length,compatibility,avgDiff}}).filter(Boolean) as {member:Member;common:number;compatibility:number;avgDiff:number}[];matches.sort((a,b)=>b.compatibility-a.compatibility||b.common-a.common||a.avgDiff-b.avgDiff);return matches[0]||null},[memberId,members,scores]);
 const person=members.find(m=>m.id===memberId);
 return <section className="section bookTwinSection" id="book-twin"><div className="glass bookTwinCard"><div className="bookTwinGlow"/><div className="bookTwinIntro"><div className="twinIcon"><UsersRound/></div><div><div className="eyebrow">Who has your exact taste?</div><h3>Find Your Book Twin</h3><p>We compare your Hook + Story scores with everyone else's and find the reader who rates books most like you.</p></div></div><div className="bookTwinPicker"><label>Who are you?</label><select className="field" value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">Select your name</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div>{memberId&&(result?<div className="twinReveal"><div className="twinSpark"><Sparkles/></div><span className="twinKicker">{person?.name}'s Book Twin is...</span><div className="twinNames"><div className="twinAvatar">{person?.name.charAt(0)}</div><Heart className="twinHeart"/><div className="twinAvatar twinAvatarMatch">{result.member.name.charAt(0)}</div></div><h4>{result.member.name}</h4><div className="compatibilityRing"><strong>{result.compatibility}%</strong><span>taste match</span></div><p className="twinDetail">Based on <strong>{result.common} book{result.common===1?'':'s'}</strong> you both rated.</p><p className="twinFine">The more books you both score, the smarter your match gets.</p></div>:<div className="twinEmpty"><Heart/><strong>No twin yet!</strong><span>Once another member has rated at least one of the same books, your match will appear here.</span></div>)}</div></section>
}