'use client';
import {useEffect,useMemo,useState} from 'react';
import {ChevronDown,LibraryBig,Save,Star} from 'lucide-react';
import {supabase} from '@/lib/supabase';

type Member={id:string;name:string};
type Book={id:string;title:string;author:string;cover_url:string|null;meeting_date:string|null;status:string};
type Score={id:string;book_id:string;member_id:string|null;display_name:string;hook_score:number;story_score:number};
type Sort='high'|'low'|'recent';

export default function MyRatings(){
 const [members,setMembers]=useState<Member[]>([]),[books,setBooks]=useState<Book[]>([]),[scores,setScores]=useState<Score[]>([]),[memberId,setMemberId]=useState(''),[sort,setSort]=useState<Sort>('high'),[addBook,setAddBook]=useState(''),[hook,setHook]=useState(4),[story,setStory]=useState(4),[msg,setMsg]=useState('');
 async function load(){if(!supabase)return;const[{data:m},{data:b},{data:s}]=await Promise.all([supabase.from('literal_trash_members').select('id,name').eq('active',true).order('name'),supabase.from('literal_trash_books').select('id,title,author,cover_url,meeting_date,status').neq('status','upcoming').order('meeting_date',{ascending:false,nullsFirst:false}),supabase.from('literal_trash_scores').select('id,book_id,member_id,display_name,hook_score,story_score')]);setMembers((m||[])as Member[]);setBooks((b||[])as Book[]);setScores((s||[])as Score[])}
 useEffect(()=>{void load();if(!supabase)return;const ch=supabase.channel('my-ratings-live').on('postgres_changes',{event:'*',schema:'public',table:'literal_trash_scores'},()=>void load()).subscribe();return()=>{void supabase?.removeChannel(ch)}},[]);
 const mine=useMemo(()=>{const map=new Map(books.map(b=>[b.id,b]));return scores.filter(s=>s.member_id===memberId&&map.has(s.book_id)).map(s=>({score:s,book:map.get(s.book_id)!})).sort((a,b)=>{const ao=(Number(a.score.hook_score)+Number(a.score.story_score))/2,bo=(Number(b.score.hook_score)+Number(b.score.story_score))/2;if(sort==='high')return bo-ao;if(sort==='low')return ao-bo;return String(b.book.meeting_date||'').localeCompare(String(a.book.meeting_date||''))})},[scores,books,memberId,sort]);
 const ratedIds=new Set(mine.map(x=>x.book.id));const missing=books.filter(b=>!ratedIds.has(b.id));const person=members.find(m=>m.id===memberId);
 async function saveMissing(){setMsg('');if(!supabase||!memberId||!addBook){setMsg('Choose a book first.');return}const member=members.find(m=>m.id===memberId);if(!member)return;const{error}=await supabase.from('literal_trash_scores').insert({book_id:addBook,member_id:memberId,display_name:member.name,hook_score:hook,story_score:story});setMsg(error?error.message:'Rating added to your history.');if(!error){setAddBook('');await load()}}
 return <section className="section myRatingsSection" id="my-ratings"><div className="sectionHead"><div><div className="eyebrow">Your personal receipts</div><h3>My Ratings</h3><p className="muted">Pick your name to see every book you rated, ranked your way.</p></div></div>
 <div className="glass ratingsProfilePicker"><LibraryBig size={22}/><div><label>Your name</label><div className="selectShell"><select className="field" value={memberId} onChange={e=>{setMemberId(e.target.value);setAddBook('');setMsg('')}}><option value="">Select your name</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><ChevronDown size={16}/></div></div></div>
 {memberId&&<><div className="personalRatingsHead"><div><span className="eyebrow">{person?.name}'s bookshelf</span><h4>{mine.length} book{mine.length===1?'':'s'} rated</h4></div><div className="sorts"><button className={'pill '+(sort==='high'?'activeSort':'')} onClick={()=>setSort('high')}>Highest rated</button><button className={'pill '+(sort==='low'?'activeSort':'')} onClick={()=>setSort('low')}>Lowest rated</button><button className={'pill '+(sort==='recent'?'activeSort':'')} onClick={()=>setSort('recent')}>Most recent</button></div></div>
 <div className="personalRatingGrid">{mine.map(({score,book},i)=>{const overall=(Number(score.hook_score)+Number(score.story_score))/2;return <article className="glass personalRatingCard" key={score.id}><div className="ratingRank">#{i+1}</div>{book.cover_url?<img src={book.cover_url} alt={book.title+' cover'} loading="lazy"/>:<div className="personalCoverFallback">LT</div>}<div className="personalRatingInfo"><span className="ratingDate">{book.meeting_date?new Date(book.meeting_date+'T12:00:00').toLocaleDateString(undefined,{month:'short',year:'numeric'}):'Book club read'}</span><h5>{book.title}</h5><p>{book.author}</p><div className="personalScoreRow"><span>Hook <strong>{Number(score.hook_score).toFixed(1)}</strong></span><span>Story <strong>{Number(score.story_score).toFixed(1)}</strong></span><span className="personalOverall"><Star size={13}/> Overall <strong>{overall.toFixed(2)}</strong></span></div></div></article>})}{!mine.length?<div className="glass personalEmpty">No ratings saved for {person?.name} yet. You can add one below.</div>:null}</div>
 {missing.length>0&&<div className="glass missingRatingBox"><div><div className="eyebrow">Missed one?</div><h4>Add a rating from the past</h4><p className="muted">Choose any book you haven't scored yet and add it to your personal history.</p></div><select className="field" value={addBook} onChange={e=>setAddBook(e.target.value)}><option value="">Choose an unrated book</option>{missing.map(b=><option value={b.id} key={b.id}>{b.title} — {b.author}</option>)}</select>{addBook&&<div className="missingScoreControls"><label>Hook <strong>{hook.toFixed(1)}</strong><input type="range" min="0" max="5" step=".1" value={hook} onChange={e=>setHook(Number(e.target.value))}/></label><label>Story <strong>{story.toFixed(1)}</strong><input type="range" min="0" max="5" step=".1" value={story} onChange={e=>setStory(Number(e.target.value))}/></label><button className="btn" onClick={()=>void saveMissing()}><Save size={15}/> Save rating</button></div>}{msg&&<p className="muted">{msg}</p>}</div>}</>}
 </section>
}