'use client';
import {useEffect,useState} from 'react';
import {X} from 'lucide-react';
import {supabase} from '@/lib/supabase';
type Book={id:string;title:string;author:string;cover_url:string|null;meeting_date:string|null;hook_avg:number;story_avg:number};
type Member={id:string;name:string};
type Score={id:string;display_name:string;hook_score:number;story_score:number;member_id:string|null};
type Post={id:string;display_name:string;post_type:string;title:string;body:string;created_at:string};
export default function PastBookModal({book,onClose}:{book:Book;onClose:()=>void}){
 const [members,setMembers]=useState<Member[]>([]),[scores,setScores]=useState<Score[]>([]),[posts,setPosts]=useState<Post[]>([]),[memberId,setMemberId]=useState(''),[hook,setHook]=useState(4),[story,setStory]=useState(4),[msg,setMsg]=useState('');
 async function load(){if(!supabase)return;const [{data:m},{data:s},{data:p}]=await Promise.all([supabase.from('literal_trash_members').select('id,name').eq('active',true).order('name'),supabase.from('literal_trash_scores').select('id,display_name,hook_score,story_score,member_id').eq('book_id',book.id).order('display_name'),supabase.from('literal_trash_board_posts').select('*').eq('book_id',book.id).order('created_at',{ascending:false})]);setMembers((m||[]) as Member[]);setScores((s||[]) as Score[]);setPosts((p||[]) as Post[])}
 useEffect(()=>{void load()},[book.id]);
 useEffect(()=>{const existing=scores.find(s=>s.member_id===memberId);if(existing){setHook(Number(existing.hook_score));setStory(Number(existing.story_score))}},[memberId,scores]);
 async function save(){if(!supabase||!memberId){setMsg('Select your name first.');return}const member=members.find(m=>m.id===memberId);if(!member)return;const existing=scores.find(s=>s.member_id===memberId);const payload={display_name:member.name,member_id:member.id,hook_score:hook,story_score:story};const result=existing?await supabase.from('literal_trash_scores').update(payload).eq('id',existing.id):await supabase.from('literal_trash_scores').insert({...payload,book_id:book.id});setMsg(result.error?result.error.message:'Your score is saved.');if(!result.error)void load()}
 return <div className="bookModalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="glass bookModal"><button className="modalClose" onClick={onClose}><X/></button><div className="modalBookHead">{book.cover_url?<img src={book.cover_url} className="modalCover" alt={`${book.title} cover`}/>:null}<div><div className="eyebrow">Trashy Past</div><h2>{book.title}</h2><p className="muted">{book.author}</p><div className="chips"><span className="chip">Hook {Number(book.hook_avg).toFixed(2)}</span><span className="chip">Story {Number(book.story_avg).toFixed(2)}</span><span className="chip">Overall {((Number(book.hook_avg)+Number(book.story_avg))/2).toFixed(2)}</span></div></div></div>
 <div className="modalColumns"><div><h3>Everyone's Scores</h3><div className="scorePeople">{scores.length?scores.map(s=><div className="personScore" key={s.id}><strong>{s.display_name}</strong><span>Hook {Number(s.hook_score).toFixed(2)}</span><span>Story {Number(s.story_score).toFixed(2)}</span><span>Overall {((Number(s.hook_score)+Number(s.story_score))/2).toFixed(2)}</span></div>):<p className="muted">No individual scores saved yet.</p>}</div><div className="pastScoreEdit"><h4>Add or update your score</h4><select className="field" value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">Select your name</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><label>Hook Score <strong>{hook.toFixed(2)}</strong><input type="range" min="0" max="5" step="0.1" value={hook} onChange={e=>setHook(Number(e.target.value))}/></label><label>Story Score <strong>{story.toFixed(2)}</strong><input type="range" min="0" max="5" step="0.1" value={story} onChange={e=>setStory(Number(e.target.value))}/></label><button className="btn" onClick={()=>void save()}>Save my score</button>{msg&&<p className="muted">{msg}</p>}</div></div>
 <div><h3>Archived Board</h3><p className="muted">Questions and discussions saved from when we read this book.</p><div className="archivedPosts">{posts.length?posts.map(p=><article className="boardPost" key={p.id}><span className="chip">{p.post_type.replace('_',' ')}</span><h4>{p.title}</h4><p>{p.body}</p><div className="boardBy">Submitted by <strong>{p.display_name}</strong></div></article>):<p className="muted">Nothing was submitted for this book.</p>}</div></div></div></div></div>
}