'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Award,ArrowLeft,Crown,Sparkles,Trophy} from 'lucide-react';
import {supabase} from '@/lib/supabase';
type Member={id:string;name:string};type Book={id:string;title:string;author:string;cover_url:string|null;meeting_date:string|null;status:string};type Vote={id:string;year:number;category:string;member_id:string;book_id:string};
const CATS=[['book_of_year','Book of the Year','The one that deserves the crown.'],['literal_trash','Literal Trash 🗑️','The book we would happily throw away.'],['best_story','Best Story','The story that stayed with us.'],['page_turner',"Couldn't Put It Down",'The fastest page-turner of the year.'],['plot_twist','Biggest Plot Twist','The moment nobody saw coming.'],['overrated','Most Overrated','We have questions.'],['underrated','Most Underrated','Deserved more love.'],['recommend','Most Likely to Recommend','The one we would actually give a friend.']] as const;
export default function Awards(){
 const year=2026,[members,setMembers]=useState<Member[]>([]),[books,setBooks]=useState<Book[]>([]),[votes,setVotes]=useState<Vote[]>([]),[memberId,setMemberId]=useState(''),[saving,setSaving]=useState('');
 async function load(){if(!supabase)return;const[{data:m},{data:b},{data:v}]=await Promise.all([supabase.from('literal_trash_members').select('id,name').eq('active',true).order('name'),supabase.from('literal_trash_books').select('id,title,author,cover_url,meeting_date,status').gte('meeting_date',year+'-01-01').lte('meeting_date',year+'-12-31').in('status',['past','current']).order('meeting_date'),supabase.from('literal_trash_award_votes').select('*').eq('year',year)]);setMembers((m||[])as Member[]);setBooks((b||[])as Book[]);setVotes((v||[])as Vote[])}
 useEffect(()=>{void load();if(!supabase)return;const ch=supabase.channel('awards-live').on('postgres_changes',{event:'*',schema:'public',table:'literal_trash_award_votes'},()=>void load()).subscribe();return()=>{void supabase?.removeChannel(ch)}},[]);
 async function vote(cat:string,bookId:string){if(!supabase||!memberId)return;setSaving(cat);const existing=votes.find(v=>v.year===year&&v.category===cat&&v.member_id===memberId);const q=existing?supabase.from('literal_trash_award_votes').update({book_id:bookId,updated_at:new Date().toISOString()}).eq('id',existing.id):supabase.from('literal_trash_award_votes').insert({year,category:cat,member_id:memberId,book_id:bookId});await q;await load();setSaving('')}
 const leaders=useMemo(()=>Object.fromEntries(CATS.map(([key])=>{const counts=new Map<string,number>();votes.filter(v=>v.category===key).forEach(v=>counts.set(v.book_id,(counts.get(v.book_id)||0)+1));const sorted=[...counts].sort((a,b)=>b[1]-a[1]);return[key,{top:sorted[0]?.[0],count:sorted[0]?.[1]||0,total:votes.filter(v=>v.category===key).length}]})),[votes]);
 const me=members.find(m=>m.id===memberId);
 return <main className="awardsPage"><div className="awardsHero"><Link href="/" className="awardsBack"><ArrowLeft/> Back to Literal Trash</Link><div className="awardsCrown"><Crown/></div><div className="eyebrow">Literal Trash Book Club presents</div><h1>The {year} Trashies</h1><p>Our books. Our opinions. Absolutely no literary authority.</p><div className="awardsLive"><span/> LIVE VOTING</div></div><section className="awardsIdentity"><label>First, who are you?</label><select value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">Select your name to vote</option>{members.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select>{me&&<small>Voting as {me.name}. Tap any book to cast or change your vote.</small>}</section><section className="awardsGrid">{CATS.map(([key,title,desc],i)=>{const l=leaders[key];const lead=books.find(b=>b.id===l.top);const myVote=votes.find(v=>v.category===key&&v.member_id===memberId)?.book_id;return <article className="awardCategory" key={key}><div className="awardNumber">{String(i+1).padStart(2,'0')}</div><Award className="awardIcon"/><h2>{title}</h2><p>{desc}</p>{l.total>0&&<div className="currentLeader"><Trophy/><span>Leading now</span><strong>{lead?.title||'Tied'}</strong><small>{l.count} vote{l.count===1?'':'s'} · {l.total} cast</small></div>}<div className="awardBooks">{books.map(b=><button key={b.id} disabled={!memberId||saving===key} className={'awardBook '+(myVote===b.id?'selected':'')} onClick={()=>void vote(key,b.id)}>{b.cover_url?<img src={b.cover_url} alt=""/>:<div className="awardCoverFallback">LT</div>}<span>{b.title}</span>{myVote===b.id&&<em><Sparkles/> Your vote</em>}</button>)}</div>{!memberId&&<div className="votePrompt">Select your name above to vote</div>}</article>})}</section><section className="awardsFooter"><Trophy/><h2>{votes.length} votes cast so far</h2><p>Results update live as the club votes. You can change any vote by choosing another book.</p></section></main>
}