'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,Check,Crown,Sparkles,Trophy,Users} from 'lucide-react';
import {supabase} from '@/lib/supabase';
type Member={id:string;name:string};type Book={id:string;title:string;author:string;cover_url:string|null;meeting_date:string|null;status:string};type Vote={id:string;year:number;category:string;member_id:string;book_id:string};
const CATS=[['book_of_year','Book of the Year','Which book deserves the crown?'],['literal_trash','Literal Trash 🗑️','Which book belongs directly in the trash?'],['best_story','Best Story','Which story stayed with you the most?'],['page_turner',"Couldn't Put It Down",'Which book had you turning pages fastest?'],['plot_twist','Biggest Plot Twist','Which book shocked you the most?'],['overrated','Most Overrated','Which book got more love than it deserved?'],['underrated','Most Underrated','Which book deserved way more love?'],['recommend','Most Likely to Recommend','Which one would you actually give to a friend?']] as const;
export default function Awards(){
 const year=2026,[members,setMembers]=useState<Member[]>([]),[books,setBooks]=useState<Book[]>([]),[votes,setVotes]=useState<Vote[]>([]),[memberId,setMemberId]=useState(''),[step,setStep]=useState(0),[choice,setChoice]=useState(''),[revealed,setRevealed]=useState(false),[saving,setSaving]=useState(false);
 async function load(){if(!supabase)return;const[{data:m},{data:b},{data:v}]=await Promise.all([supabase.from('literal_trash_members').select('id,name').eq('active',true).order('name'),supabase.from('literal_trash_books').select('id,title,author,cover_url,meeting_date,status').gte('meeting_date',year+'-01-01').lte('meeting_date',year+'-12-31').in('status',['past','current']).order('meeting_date'),supabase.from('literal_trash_award_votes').select('*').eq('year',year)]);setMembers((m||[])as Member[]);setBooks((b||[])as Book[]);setVotes((v||[])as Vote[])}
 useEffect(()=>{void load();if(!supabase)return;const ch=supabase.channel('awards-live-room').on('postgres_changes',{event:'*',schema:'public',table:'literal_trash_award_votes'},()=>void load()).subscribe();return()=>{void supabase?.removeChannel(ch)}},[]);
 const cat=CATS[step]; const categoryKey=cat?cat[0]:''; const catVotes=votes.filter(v=>v.category===categoryKey); const mySaved=votes.find(v=>v.category===categoryKey&&v.member_id===memberId);
 useEffect(()=>{setChoice(mySaved?.book_id||'');setRevealed(Boolean(mySaved))},[step,memberId,mySaved?.book_id]);
 const results=books.map(b=>{const bv=catVotes.filter(v=>v.book_id===b.id);const voters:string[]=[];bv.forEach(v=>{const m=members.find(x=>x.id===v.member_id);if(m)voters.push(m.name)});return{book:b,count:bv.length,voters}}).sort((a,b)=>b.count-a.count);
 async function submit(){if(!supabase||!memberId||!choice||!categoryKey)return;setSaving(true);const existing=votes.find(v=>v.year===year&&v.category===categoryKey&&v.member_id===memberId);if(existing)await supabase.from('literal_trash_award_votes').update({book_id:choice,updated_at:new Date().toISOString()}).eq('id',existing.id);else await supabase.from('literal_trash_award_votes').insert({year,category:categoryKey,member_id:memberId,book_id:choice});await load();setSaving(false);setRevealed(true)}
 function next(){if(step<CATS.length-1){setStep(s=>s+1);setChoice('');setRevealed(false);window.scrollTo({top:0,behavior:'smooth'})}} async function resetAwards(){if(!supabase)return;if(!window.confirm('Reset all 2026 Trashies votes and start over?'))return;setSaving(true);const{error}=await supabase.rpc('literal_trash_reset_awards',{p_year:year});if(!error){setVotes([]);setStep(0);setChoice('');setRevealed(false);window.scrollTo({top:0,behavior:'smooth'})}setSaving(false)}
 const done=step===CATS.length-1&&revealed,me=members.find(m=>m.id===memberId);
 if(!memberId)return <main className="liveAwards"><div className="liveAwardsTop"><Link href="/"><ArrowLeft/> Home</Link></div><section className="awardsWelcome"><div className="welcomeCrown"><Crown/></div><span className="awardsMini">LITERAL TRASH BOOK CLUB</span><h1>The {year}<br/><em>Trashies</em></h1><p>Vote live. See what everyone thinks. Crown the winners.</p><div className="joinBox"><label>Who are you?</label><select value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">Select your name</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div></section></main>;
 if(!cat)return null;
 return <main className="liveAwards"><header className="liveGameHeader"><button onClick={()=>setMemberId('')}>{me?.name}</button><div className="liveHeaderActions"><span><b>{step+1}</b> / {CATS.length}</span><button className="resetAwardsButton" onClick={()=>void resetAwards()}>Reset</button></div></header><div className="gameProgress"><i style={{width:((step+1)/CATS.length*100)+'%'}}/></div><section className="questionScreen"><span className="questionLabel">AWARD {String(step+1).padStart(2,'0')}</span><h1>{cat[1]}</h1><p>{cat[2]}</p>{!revealed?<><div className="mobileBookChoices">{books.map(b=><button key={b.id} className={'mobileBookChoice '+(choice===b.id?'picked':'')} onClick={()=>setChoice(b.id)}>{b.cover_url?<img src={b.cover_url} alt=""/>:<div className="mobileCoverFallback">LT</div>}<div><strong>{b.title}</strong><small>{b.author}</small></div>{choice===b.id&&<span className="choiceCheck"><Check/></span>}</button>)}</div><button className="submitAwardVote" disabled={!choice||saving} onClick={()=>void submit()}>{saving?'Saving...':'Lock In My Vote'} <Sparkles/></button></>:<div className="resultsReveal"><div className="resultsLive"><span/> LIVE RESULTS <Users/> {catVotes.length}</div><div className="resultRows">{results.filter(r=>r.count>0).map((r,i)=>{const pct=catVotes.length?Math.round(r.count/catVotes.length*100):0;return <div className={'resultRow '+(i===0?'leader':'')} key={r.book.id}><div className="resultRank">{i===0?<Trophy/>:i+1}</div>{r.book.cover_url&&<img src={r.book.cover_url} alt=""/>}<div className="resultInfo"><div className="resultTitleLine"><strong>{r.book.title}</strong><b>{pct}%</b></div><div className="resultBar"><i style={{width:pct+'%'}}/></div><small>{r.count} vote{r.count===1?'':'s'}</small><div className="resultVoters">{r.voters.map(name=><span key={name}>{name}</span>)}</div></div></div>})}</div><div className="savedVote"><Check/> Your vote is saved</div>{!done?<button className="nextAward" onClick={next}>Next Award <span>→</span></button>:<div className="awardsComplete"><Crown/><h2>Ballot Complete!</h2><p>All of your votes are saved.</p></div>}</div>}</section></main>
